arb-dir: assets/translations
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: Ll
output-dir: lib/src/core/presentation/localizations
synthetic-package: false