on:
    push: 
        branches: 
            - master
name: Build The App
jobs: 
    build:
        name: Build and release new apk
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v2
              with: 
                distribution: zulu
                java-version: '19'
            - uses: subosito/flutter-action@v2
              with: 
                channel: stable
            - run: flutter pub get
            - run: flutter build apk --debug --split-per-abi

            - name: Push to Releases
              uses: ncipollo/release-action@v1
              with: 
                artifacts: build/app/outputs/apk/debug/*
                tag: v0.0.1
                token: ${{ secrets.REPO_SECRET_TOKEN }} 


